#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: "Andrea Tomasi CV"
url: 'https://treere/github.io'
baseurl: '/cv' #change it according to your repository name
description: "Andrea Tomasi CV"
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: blue # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
analytics: UA-165410693-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: default # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
